<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin name="four_wheel_drive_plugin" filename="libgazebo_ros_skid_steer_drive.so">
                
            <!-- Wheel Joints -->
            <leftFrontJoint>wheel_joint_front_left</leftFrontJoint>
            <rightFrontJoint>wheel_joint_front_right</rightFrontJoint>
            <leftRearJoint>wheel_joint_rear_left</leftRearJoint>
            <rightRearJoint>wheel_joint_rear_right</rightRearJoint>
            
            <!-- Robot and Wheel Parameters -->
            <wheelSeparation>${wheel_base}</wheelSeparation>
            <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
            <robotBaseFrame>robot_footprint</robotBaseFrame>

            <torque>20</torque>
            <!-- Output -->
            <topicName>cmd_vel</topicName>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>

            <commandTopic>cmd_vel</commandTopic>
            <topic_name_twist>cmd_vel</topic_name_twist>
            <topic_name_odometry>odom</topic_name_odometry>
            <topic_name_joint>joint</topic_name_joint>

            <broadcastTF>true</broadcastTF>

            <covariance_x>0.0001</covariance_x>
            <covariance_y>0.0001</covariance_y>
            <covariance_yaw>0.01</covariance_yaw>
            
        </plugin>
    </gazebo>

</robot>
